name: "tag"
on:
  push:
    branches:
      - master
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        uses: minddocdev/mou-version-action@v1.0.0
        env:
          token: ${{ github.token }}
